version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks: 
      - bluecherry_net
    volumes:
      - ./database:/var/lib/mysql
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports: 
       - 3306
    #options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: $TZ
  bc-server:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    network: bluecherry_net
#      args:
        # MYSQL_ADMIN_PASSWORD: $MYSQL_ADMIN_PASSWORD
        # MYSQL_ADMIN_LOGIN: $MYSQL_ADMIN_LOGIN
        # BLUECHERRY_DB_USER: $BLUECHERRY_DB_USER
        # BLUECHERRY_DB_PASSWORD: $BLUECHERRY_DB_PASSWORD
        # BLUECHERRY_DB_NAME: $BLUECHERRY_DB_NAME
        # BLUECHERRY_DB_HOST: $BLUECHERRY_DB_HOST
        # BLUECHERRY_DB_ACCESS_HOST: $BLUECHERRY_DB_ACCESS_HOST
        # BLUECHERRY_LINUX_GROUP_ID: $BLUECHERRY_LINUX_GROUP_ID
        # BLUECHERRY_LINUX_USER_ID: $BLUECHERRY_LINUX_USER_ID    
  networks:
  bluecherry_net:
    name: bluecherry_net     
